
name: CI workflow

on: 
  push:
    branches: [master]

jobs: 
  test: 
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node 15
      uses: actions/setup-node@v1
      with:
        node-version: '15'
        check-latest: true
      
    - name: Check out code 
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Unit tests
      run: npm test