
name: CI workflow

on: 
  push:
    branches: [master]

jobs: 
  test: 
    name: Unit tests 
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node 15
      uses: actions/setup-node@v1
      with:
        node-version: '15'
      
    - name: Check out code 
      uses: actions/checkout@v2

    - name: Build application
      working-directory: ./app
      run: npm install

    - name: Unit testing
      working-directory: ./app
      run: npm test